version: '3'
services:
  DB:
    hostname: classt-test
    image: postgres:13-alpine
    container_name: classt-test-db
    networks:
      - classt-test-network
    restart: on-failure
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=classt
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=q1w2e3
  redis:
    hostname: classt-test
    image: redis:6-alpine
    container_name: classt-test-redis
    networks:
      - classt-test-network
    restart: on-failure
    ports:
      - 6379:6379

networks:
  classt-test-network:
